### ISSUE TITLE
Access to `window.tizen` and `window.webapis` from cloud app

### ISSUE THREAD

**Issue by vitalets** [SamsungDForum/SmartViewSDKFakeCloudApp#1]
Hi

it is not clear from docs is it possible to use `window.tizen` and `window.webapis` from cloud app or it is only for installed apps.
Thx!

**Comment by monster-mj** [comment]
Hi @vitalets 
 window.tizen  and  window.webapis  are  tizen API, so U can use only installed app.

**Comment by vitalets** [comment]
@monster-mj thanks a lot for answering my questions!
Could I ask you another one related to cloud/installed app:

First I as going to use installed app instead of cloud app, but a very important Smart View SDK method `Application.install()` did not work for me for both android and javascript versions:

https://smartviewsdk.github.io/API-GUIDE/js-api/docs/api.html#Application+install

I tried to install apps that really exist in samsung store, for example `VFxTEnWeLb.Yandex`:
that is for http://www.samsung.com/ru/samsung-tv-apps/#yandex.html
but always get 404 response and installation process does not run on tv.

My code is:
```js
msf.remote(`http://37.140.172.153:8001/api/v2/`, function (err, service) {
  var app = service.application('VFxTEnWeLb.Yandex', 'com.samsung.multiscreen.helloworld');
  app.connect({name: 'Vitalets'}, function(err, client){
   if(err.code === 404){
        app.install(function(err){
           console.log('install cb')
        });
  }
 });
});
```

Could help how to install apps with SmartView SDK? 
Or maybe there should be some setup on seller site?

**Comment by monster-mj** [comment]
Hi, @vitalets 
I got your point, but U had some mistake to use AppID.
You know, ' VFxTEnWeLb.Yandex' is issued TizenSDK(we called Tizen App ID)
But, U must use AppID that composed of number issued by appstore(**_e.g. 111299000796_**)
var app = service.application(**_'VFxTEnWeLb.Yandex'_**, 'com.samsung.multiscreen.helloworld');
var app = service.application(**_'111299000796'_**, 'com.samsung.multiscreen.helloworld');

**Comment by vitalets** [comment]
thanks @monster-mj ! I will try! 
I think it would be great to add this note to docs as it maybe not clear that there are two different app ids.

**Comment by vitalets** [comment]
With appstore id everything works fine!
Thanks again!
